#!/usr/bin/env python3
"""MasterVP BTC M3 event taxonomy pre-gate.

Uses the existing BTC M3 trade stream. This is not a sweep; it checks whether
any pre-entry variables deserve a future BTC M3 build.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
TRADES = ROOT / "cpp_core" / "tools" / "trades_cpp_btcusd_2025_M3.csv"
OUT_DIR = ROOT / "research" / "mastervp_parity" / "btc_m3_event_taxonomy_2026-06-28"


def metrics(df: pd.DataFrame) -> dict[str, float | int]:
    wins = df["realizedUsd"] > 0
    gross_win = df.loc[wins, "realizedUsd"].sum()
    gross_loss = -df.loc[~wins, "realizedUsd"].sum()
    return {
        "n": int(len(df)),
        "net": float(df["realizedUsd"].sum()),
        "usd_per_trade": float(df["realizedUsd"].mean()) if len(df) else np.nan,
        "pf": float(np.inf if gross_loss <= 0 else gross_win / gross_loss),
        "win_rate": float(wins.mean()) if len(df) else np.nan,
        "mfeR_mean": float(df["mfeR"].mean()) if "mfeR" in df else np.nan,
    }


def quartile_table(df: pd.DataFrame, col: str) -> pd.DataFrame:
    x = df[[col, "realizedUsd", "mfeR"]].dropna().copy()
    if x[col].nunique() < 4:
        return pd.DataFrame()
    x["bucket"] = pd.qcut(x[col], 4, duplicates="drop")
    rows = []
    for bucket, g in x.groupby("bucket", observed=False):
        rows.append({"feature": col, "bucket": str(bucket), **metrics(g)})
    return pd.DataFrame(rows)


def category_table(df: pd.DataFrame, col: str) -> pd.DataFrame:
    rows = []
    for key, g in df.groupby(col, dropna=False):
        rows.append({"feature": col, "bucket": str(key), **metrics(g)})
    return pd.DataFrame(rows)


def monotone_score(tab: pd.DataFrame) -> str:
    if tab.empty or len(tab) < 4:
        return "n/a"
    vals = tab["usd_per_trade"].to_numpy(float)
    diffs = np.diff(vals)
    if np.all(diffs >= 0):
        return "monotone_up"
    if np.all(diffs <= 0):
        return "monotone_down"
    return "non_monotone"


def df_to_markdown(df: pd.DataFrame, floatfmt: str = ".3f") -> str:
    if df.empty:
        return "(empty)"
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for _, row in df.iterrows():
        vals = []
        for col in cols:
            val = row[col]
            if isinstance(val, float):
                vals.append(format(val, floatfmt))
            else:
                vals.append(str(val))
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(TRADES)
    numeric_features = ["brkDistAtr", "adx", "diSpread", "runwayAtr", "nodeNet", "spreadAtr"]
    categorical_features = ["dir", "session", "entryReason", "exitTag", "regimeTrend"]

    base = pd.DataFrame([{"feature": "BASE", "bucket": "all", **metrics(df)}])
    q_tabs = [quartile_table(df, col) for col in numeric_features if col in df]
    c_tabs = [category_table(df, col) for col in categorical_features if col in df]
    all_tabs = pd.concat([base] + q_tabs + c_tabs, ignore_index=True)
    all_tabs.to_csv(OUT_DIR / "btc_m3_event_taxonomy.csv", index=False)

    feature_scores = []
    for col, tab in zip(numeric_features, q_tabs):
        if tab.empty:
            continue
        feature_scores.append(
            {
                "feature": col,
                "monotone": monotone_score(tab),
                "best_bucket_usd_per_trade": tab["usd_per_trade"].max(),
                "worst_bucket_usd_per_trade": tab["usd_per_trade"].min(),
                "best_bucket_pf": tab.loc[tab["usd_per_trade"].idxmax(), "pf"],
            }
        )
    score_df = pd.DataFrame(feature_scores)
    score_df.to_csv(OUT_DIR / "btc_m3_feature_scores.csv", index=False)

    positive = score_df[
        (score_df["monotone"] != "non_monotone")
        & (score_df["best_bucket_usd_per_trade"] > 0)
        & (score_df["best_bucket_pf"] > 1.15)
    ]
    if positive.empty:
        verdict = (
            "STOP: no numeric pre-entry variable shows a clean monotone, economically coherent BTC M3 edge. "
            "Do not run new BTC M3 sweeps yet."
        )
    else:
        verdict = (
            "PASS-WARN: at least one numeric variable has a monotone positive bucket. Treat as a research lead, "
            "not a lock, because BTC still lacks cross-feed/cost/MT5 confirmation."
        )

    md = f"""# MasterVP BTC M3 Event Taxonomy Pre-Gate

Generated by `research/mastervp_parity/btc_m3_event_taxonomy.py`.

## Codex-Step-5 Verdict

{verdict}

## Base Metrics

{df_to_markdown(base)}

## Numeric Feature Scores

{df_to_markdown(score_df)}

## Full Taxonomy

{df_to_markdown(all_tabs)}

## Decision Use

BTC M3 gets no new alpha build unless a variable shows monotone MFE/PF structure, survives cost stress, and
then MT5 confirms. Existing evidence remains strongly negative, so this pre-gate is deliberately strict.
"""
    (OUT_DIR / "BTC_M3_EVENT_TAXONOMY.md").write_text(md)
    print(OUT_DIR / "BTC_M3_EVENT_TAXONOMY.md")


if __name__ == "__main__":
    main()
