#include "kk/mastervp/indicators.hpp"
#include "kk/common/test.hpp"
#include <vector>

using kk::ind::vector;

static void test_ema_recursive() {
    std::vector<double> x{1, 2, 3, 4};
    auto o = kk::ind::ema(x, 2);            // alpha = 2/3
    const double a = 2.0 / 3.0;
    std::vector<double> e{1};
    for (size_t i = 1; i < x.size(); ++i) e.push_back(a * x[i] + (1 - a) * e[i - 1]);
    for (size_t i = 0; i < x.size(); ++i) KK_CHECK_NEAR(o[i], e[i], 1e-12);
}

static void test_wilder_rma() {
    std::vector<double> x{10, 11, 12, 13};
    auto o = kk::ind::wilder_rma(x, 4);     // alpha = 0.25
    KK_CHECK_NEAR(o[3], 11.265625, 1e-9);
}

static void test_true_range() {
    std::vector<double> h{10, 12}, l{8, 9}, c{9, 11};
    auto tr = kk::ind::true_range(h, l, c);
    KK_CHECK_NEAR(tr[0], 2.0, 1e-12);        // high-low
    KK_CHECK_NEAR(tr[1], 3.0, 1e-12);        // max(3, |12-9|, |9-9|)
}

static void test_rsi_all_gains_is_100() {
    std::vector<double> c;
    for (int i = 0; i < 300; ++i) c.push_back(100.0 + i * (100.0 / 299.0));
    auto r = kk::ind::rsi(c, 14);
    KK_CHECK(r.back() > 99.9);
    for (double v : r) KK_CHECK(v >= 0.0 && v <= 100.0);
}

static void test_atr_positive() {
    std::vector<double> h, l, c;
    for (int i = 0; i < 100; ++i) { double p = 100 + i; h.push_back(p + 1); l.push_back(p - 1); c.push_back(p); }
    auto a = kk::ind::atr(h, l, c, 14);
    for (size_t i = 14; i < a.size(); ++i) KK_CHECK(a[i] > 0.0);
}

static void test_dmi_uptrend_plus_dominates() {
    std::vector<double> h, l, c;
    for (int i = 0; i < 200; ++i) { double p = 100 + i * 0.5; h.push_back(p + 1); l.push_back(p - 1); c.push_back(p); }
    auto d = kk::ind::dmi_adx(h, l, c, 14);
    double pd = 0, md = 0;
    for (size_t i = 150; i < h.size(); ++i) { pd += d.plus_di[i]; md += d.minus_di[i]; }
    KK_CHECK(pd > md);
    for (size_t i = 30; i < h.size(); ++i) {
        KK_CHECK(d.adx[i] >= 0 && d.adx[i] <= 100);
        KK_CHECK(d.plus_di[i] >= 0 && d.plus_di[i] <= 100);
    }
}

// Golden fixture: dmi_adx_mt5 must reproduce the validated MT5-iADX reference
// (values generated by cpp_core/tools/validate_parity_py.py's proven formula on a
// deterministic synthetic series). Guards the iADX EMA-smoothing port from regressing
// back to textbook Wilder.
static void test_dmi_mt5_golden() {
    std::vector<double> h{101.500000,103.766654,104.847695,104.454760,103.414959,103.044940,104.154471,106.433628,108.687336,109.739780,109.324237,108.284928,107.938128,109.076033,111.367246,113.607569,114.631316,114.193481,113.155156,112.831870,113.998026,116.300845,118.527347,119.522305,119.062501,118.025651,117.726169,118.920443,121.234416,123.446666,124.412752,123.931305,122.896421,122.621026,123.843278,126.167949,128.365519,129.302657,128.799903,127.767476};
    std::vector<double> l{98.700000,100.966654,102.047695,101.654760,100.614959,100.244940,101.354471,103.633628,105.887336,106.939780,106.524237,105.484928,105.138128,106.276033,108.567246,110.807569,111.831316,111.393481,110.355156,110.031870,111.198026,113.500845,115.727347,116.722305,116.262501,115.225651,114.926169,116.120443,118.434416,120.646666,121.612752,121.131305,120.096421,119.821026,121.043278,123.367949,125.565519,126.502657,125.999903,124.967476};
    std::vector<double> c{100.400000,102.617687,103.563816,102.983055,101.748500,101.224482,102.258474,104.559045,106.925878,108.155461,107.937702,107.068396,106.822196,107.966668,110.168807,112.246223,113.073116,112.452676,111.290704,110.933001,112.162397,114.610631,117.029118,118.215627,117.900043,116.924770,116.589148,117.658411,119.789111,121.804696,122.608877,122.039924,121.013358,120.840067,122.233213,124.755725,127.129646,128.178467,127.695385,126.585802};
    auto d = kk::ind::dmi_adx_mt5(h, l, c, 14);
    KK_CHECK_NEAR(d.adx[25],      58.9267952799, 1e-5);
    KK_CHECK_NEAR(d.plus_di[25],  25.8080030980, 1e-5);
    KK_CHECK_NEAR(d.minus_di[25], 11.5488787415, 1e-5);
    KK_CHECK_NEAR(d.adx[39],      52.4224783444, 1e-5);
    KK_CHECK_NEAR(d.plus_di[39],  25.2198440589, 1e-5);
    KK_CHECK_NEAR(d.minus_di[39], 11.8660057793, 1e-5);
}

static void run_all() {
    KK_RUN(test_ema_recursive);
    KK_RUN(test_wilder_rma);
    KK_RUN(test_true_range);
    KK_RUN(test_rsi_all_gains_is_100);
    KK_RUN(test_atr_positive);
    KK_RUN(test_dmi_uptrend_plus_dominates);
    KK_RUN(test_dmi_mt5_golden);
}

KK_TEST_MAIN()
