#!/usr/bin/env python3
"""Pre-gate simple VP-context rules for KenKem M1.

This intentionally tests only obvious rules suggested by the causal VP audit.
It rejects rules that cut below MinTRL or rely on one quarter.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
IN = ROOT / "research" / "kenkem_parity" / "vp_entry_audit" / "kenkem_m1_d5_e4long_vp_joined.csv"
OUT_DIR = ROOT / "research" / "kenkem_parity" / "vp_entry_audit"
MINTRL = 122


def metrics(df: pd.DataFrame) -> dict[str, float | int]:
    wins = df["realizedUsd"] > 0
    gross_win = df.loc[wins, "realizedUsd"].sum()
    gross_loss = -df.loc[~wins, "realizedUsd"].sum()
    return {
        "n": int(len(df)),
        "net": float(df["realizedUsd"].sum()),
        "pf": float(np.inf if gross_loss <= 0 else gross_win / gross_loss),
        "win_rate": float(wins.mean()) if len(df) else 0.0,
        "mfeR_mean": float(df["mfeR"].mean()) if len(df) else np.nan,
        "mintrl_pass": bool(len(df) >= MINTRL),
    }


def quarter_table(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for q, g in df.groupby("quarter"):
        m = metrics(g)
        rows.append({"quarter": str(q), **m})
    return pd.DataFrame(rows)


def df_to_markdown(df: pd.DataFrame, floatfmt: str = ".3f") -> str:
    if df.empty:
        return "(empty)"
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for _, row in df.iterrows():
        vals = []
        for col in cols:
            val = row[col]
            if isinstance(val, float):
                vals.append(format(val, floatfmt))
            else:
                vals.append(str(val))
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines)


def main() -> None:
    df = pd.read_csv(IN)
    df["entry_ts"] = pd.to_datetime(df["entry_ts"])
    df["quarter"] = df["entry_ts"].dt.to_period("Q")
    rules = {
        "BASE": np.ones(len(df), dtype=bool),
        "No_inside_value": df["vp_location"] != "inside_value",
        "No_E2_inside": ~((df["kind"] == "E2") & (df["vp_location"] == "inside_value")),
        "E4_above_only": (df["kind"] != "E4") | (df["vp_location"] == "above_value"),
        "Entry_family_obvious_cells": (
            ((df["kind"] == "E1") & (df["vp_location"].isin(["below_value", "inside_value"])))
            | ((df["kind"] == "E2") & (df["vp_location"].isin(["above_value", "below_value"])))
            | ((df["kind"] == "E4") & (df["vp_location"] == "above_value"))
        ),
    }

    rows = []
    q_tables = {}
    for name, mask in rules.items():
        sub = df.loc[mask].copy()
        m = metrics(sub)
        q = quarter_table(sub)
        q_tables[name] = q
        rows.append(
            {
                "rule": name,
                **m,
                "quarters_positive": int((q["net"] > 0).sum()) if not q.empty else 0,
                "quarters_total": int(len(q)),
                "worst_quarter_net": float(q["net"].min()) if not q.empty else np.nan,
            }
        )
    summary = pd.DataFrame(rows)
    summary.to_csv(OUT_DIR / "vp_candidate_rule_summary.csv", index=False)
    for name, q in q_tables.items():
        q.to_csv(OUT_DIR / f"vp_rule_{name}_quarters.csv", index=False)

    reject_reasons = []
    for _, row in summary.iterrows():
        if row["rule"] == "BASE":
            continue
        reasons = []
        if not row["mintrl_pass"]:
            reasons.append("fails MinTRL")
        if row["quarters_positive"] < max(2, row["quarters_total"] - 1):
            reasons.append("weak quarter coverage")
        if row["pf"] <= summary.loc[summary["rule"] == "BASE", "pf"].iloc[0]:
            reasons.append("PF not better than base")
        reject_reasons.append((row["rule"], ", ".join(reasons) if reasons else "pre-gate candidate"))

    reasons_md = "\n".join(f"- **{name}:** {reason}" for name, reason in reject_reasons)
    md = f"""# KenKem M1 VP Candidate Rule Pre-Gate

Generated by `research/kenkem_parity/kenkem_m1_vp_candidate_rules.py`.

## Codex-Step-4 Verdict

The obvious VP filters are **not ready for code changes**. Some improve PF or net, but the stronger filters
cut the sample below MinTRL or remain too quarter-sensitive. VP should stay a research/state feature until more
trade evidence or a sizing-only meta-label can be tested.

## Rule Summary

{df_to_markdown(summary)}

## Pre-Gate Decisions

{reasons_md}

## Consequence

Stop before changing the KenKem EA. The next self-contained work is not a VP entry filter; it is either:

1. build the unified trade/event schema so VP context can be evaluated across more runs, or
2. test VP as a **sizing/state variable** rather than a hard entry filter, because hard filters spend scarce
   KenKem sample size.
"""
    (OUT_DIR / "KENKEM_M1_VP_CANDIDATE_RULES.md").write_text(md)
    print(OUT_DIR / "KENKEM_M1_VP_CANDIDATE_RULES.md")


if __name__ == "__main__":
    main()
